POST http://localhost:3000/api/services
content-type: application/json

{
    "name": "Algum serviço",
    "description": "Alguma descrção",
    "price": 1400,
    "image": "https://images.pexels.com/photos/15350765/pexels-photo-15350765/free-photo-of-monaco-palacio-castelo-automobilismo.jpeg?auto=compress&cs=tinysrgb&w=600"
}

###
GET http://localhost:3000/api/services


###
GET http://localhost:3000/api/services/666ddf6b6e9167c6ac960bad